"""Added unique non-null email field on user model.

Revision ID: fb50d0a7760e
Revises: 2ddd916f2337
Create Date: 2018-10-25 17:32:35.988877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb50d0a7760e'
down_revision = '2ddd916f2337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
